use std::io::{self, Write};

pub fn process_png_to_gcode<W: Write>(
    input_path: &str,
    writer: &mut W,
    feed_rate: i32,
    laser_power: i32,
    target_width_mm: f64,
    target_height_mm: f64,
    invert_colors: bool,
) -> io::Result<()> {
    let img = image::open(input_path).map_err(|e| io::Error::new(io::ErrorKind::InvalidData, e))?;
    let grayscale = img.into_luma8();
    let (width, height) = grayscale.dimensions();

    let pixel_size_x_mm = target_width_mm / width as f64;
    let pixel_size_y_mm = target_height_mm / height as f64;

    writeln!(writer, 
        "{}{}{}{}{}{}{}{}{}{}{}",
        "; Generated by GTRACE Core Engine Software\n",
        "; Author : Ken Panya Triprom\n",
        "; Created for Educational Porpose @KMITL\n",
        "; Gtrace Version : 1.4.0\n",
        "G17 ; Set oprate plane to XY\n",
        "G21 : Set units to milimeters\n",
        "G54 ; Set work coordinate system\n",
        "G90 ; Absolute positioning\n",
        "F{} ; Set feed rate\n",
        "M4 ; Dynamic Laser Mode ON",
        feed_rate)?;

    for y in 0..height {
        let physical_y = -(y as f64 * pixel_size_y_mm);
        let mut is_laser_on = false;

        for x in 0..width {
            let pixel_val = grayscale.get_pixel(x, y)[0];
            
            let is_dark = if invert_colors {
                pixel_val > 127
            } else {
                pixel_val < 127
            };

            let physical_x = x as f64 * pixel_size_x_mm;

            if is_dark && !is_laser_on {
                writeln!(writer, "G0 X{:.3} Y{:.3} S0", physical_x, physical_y)?;
                is_laser_on = true;
            } else if !is_dark && is_laser_on {
                writeln!(writer, "G1 X{:.3} Y{:.3} S{}", physical_x, physical_y, laser_power)?;
                is_laser_on = false;
            }
        }

        if is_laser_on {
            let end_x_mm = width as f64 * pixel_size_x_mm;
            writeln!(writer, "G1 X{:.3} Y{:.3} S{}", end_x_mm, physical_y, laser_power)?;
        }
    }

    writeln!(writer,
        "{}{}{}{}",
        "M5 ; Turn off laser\n",
        "G0 X0 Y0 ; Return to origin position \n",
        "M30 ; End of program operation\n",
        "; Thank you for using & Support GTRACE ;)")?;
    
    Ok(())
}