use geo::LineString;
use std::io::{self, Write};

pub fn write_gcode<W: Write>(
    writer: &mut W,
    isolation_paths: &[LineString<f64>],
    feed_rate: i32,
    laser_power: i32,
    mirror_x: i32,
    mirror_y: i32,
) -> io::Result<()> {
    writeln!(
        writer,
        "; Generated by GTRACE Core Engine Software\n\
         ; Author : Ken Panya Triprom\n\
         ; Created for Educational Porpose @KMITL\n\
         ; Gtrace Version : 1.4.0\n\
         G17 ; Set the operate plane to XY\n\
         G21 ; Set units to milimeters\n\
         G54 ; Set work coordinate system\n\
         G90 ; Absolute positioning\n\
         F{} ; Set feed rate\n\
         M03 ; Turn on Operation laser",
        feed_rate
    )?;

    let mut min_x = f64::INFINITY;
    let mut max_x = f64::NEG_INFINITY;
    let mut min_y = f64::INFINITY;
    let mut max_y = f64::NEG_INFINITY;

    for path in isolation_paths {
        for c in path.coords() {
            min_x = min_x.min(c.x);
            max_x = max_x.max(c.x);
            min_y = min_y.min(c.y);
            max_y = max_y.max(c.y);
        }
    }

    let get_x = |x: f64| -> f64 { if mirror_x == 1 { max_x + min_x - x } else { x } };
    let get_y = |y: f64| -> f64 { if mirror_y == 1 { max_y + min_y - y } else { y } };

    for (path_idx, path) in isolation_paths.iter().enumerate() {
        writeln!(writer, "; Isolation Path {}", path_idx + 1)?;

        for (point_idx, c) in path.coords().enumerate() {
            let px = get_x(c.x);
            let py = get_y(c.y);
            if point_idx == 0 {
                writeln!(writer, "G0 X{:.4} Y{:.4} S0", px, py)?;
            } else {
                writeln!(writer, "G1 X{:.4} Y{:.4} S{}", px, py, laser_power)?;
            }
        }
    }

    writeln!(
        writer,
        "M05 ; Turn off laser\n\
         G0 X0 Y0 ; Return to origin position\n\
         M30 ; End of program operation\n\
         ; Thank you for using & Support GTRACE ;)"
    )?;
    Ok(())
}
