use geo::LineString;
use std::io::{self, Write};

pub fn write_gcode<W: Write>(
    writer: &mut W,
    isolation_paths: &[LineString<f64>],
    feed_rate: i32,
    laser_power: i32,
    mirror_x: i32,
) -> io::Result<()> {
    writeln!(writer, "; Generated by GTRACE Core Engine")?;
    writeln!(writer, "G21 ; Set units to millimeters")?;
    writeln!(writer, "G90 ; Absolute positioning")?;
    writeln!(writer, "F{} ; Set feed rate", feed_rate)?;

    let mut min_x = f64::MAX;
    let mut max_x = f64::MIN;

    for path in isolation_paths {
        for c in path.coords() {
            if c.x < min_x {
                min_x = c.x;
            }
            if c.x > max_x {
                max_x = c.x;
            }
        }
    }

    let get_x = |x: f64| -> f64 { if mirror_x == 1 { max_x + min_x - x } else { x } };

    for (path_idx, path) in isolation_paths.iter().enumerate() {
        writeln!(writer, "; Isolation Path {}", path_idx + 1)?;

        for (point_idx, c) in path.coords().enumerate() {
            let px = get_x(c.x);
            if point_idx == 0 {
                writeln!(writer, "G0 X{:.4} Y{:.4} S0", px, c.y)?;
            } else {
                writeln!(writer, "G1 X{:.4} Y{:.4} S{}", px, c.y, laser_power)?;
            }
        }
    }

    writeln!(writer, "M5 ; Turn off laser")?;
    writeln!(writer, "M2 ; End of program")?;
    Ok(())
}
