use std::ffi::CStr;
use std::fs::File;
use std::io::{self, BufRead, Write};
use std::os::raw::c_char;
use std::collections::HashMap;
use geo::{coord, LineString, Polygon, MultiPolygon};
use geo::BooleanOps;

#[derive(Debug)]
pub struct SolderPad {
    pub x: f64,
    pub y: f64,
    pub diameter: f64,
}

#[derive(Debug)]
pub struct LineSegment {
    pub start_x: f64,
    pub start_y: f64,
    pub end_x: f64,
    pub end_y: f64,
    pub thickness: f64
}

fn create_circle(x: f64, y: f64, radius: f64) -> Polygon<f64> {
    let mut points = vec![];
    let sides = 12;
    for i in 0..sides {
        let angle = 2.0 * std::f64::consts::PI * (i as f64) / (sides as f64);
        points.push(coord! {
            x: x + radius * angle.cos(),
            y: y + radius * angle.sin()
        });
    }
    points.push(points[0]); 
    Polygon::new(LineString::new(points), vec![])
}

fn line_to_polygon(segment: &LineSegment) -> Polygon<f64> {
    let dx = segment.end_x - segment.start_x;
    let dy = segment.end_y - segment.start_y;
    let length = (dx * dx + dy * dy).sqrt();

    if length < 0.0001 {
        let radius = segment.thickness / 2.0;
        let mut points = vec![];
        let sides = 8;

        for i in 0..sides {
            let angle = 2.0 * std::f64::consts::PI * (i as f64) / (sides as f64);
            points.push(coord! {
                x: segment.start_x + radius * angle.cos(),
                y: segment.start_y + radius * angle.sin()
            });
        }
        points.push(points[0]);
        
        return Polygon::new(LineString::new(points), vec![]);
    }

    let nx = -dy / length;
    let ny = dx / length;
    let half_t = segment.thickness / 2.0;

    let p1 = coord! {
        x: segment.start_x + nx * half_t,
        y: segment.start_y + ny * half_t
    };

    let p2 = coord! {
        x: segment.start_x - nx * half_t,
        y: segment.start_y - ny * half_t
    };

    let p3 = coord! {
        x: segment.end_x - nx * half_t,
        y: segment.end_y - ny * half_t
    };

    let p4 = coord! {
        x: segment.end_x + nx * half_t,
        y: segment.end_y + ny * half_t
    };

    Polygon::new(LineString::new(vec![p1, p2, p3, p4, p1]), vec![])
}

#[derive(Debug)]
pub struct CncState {
    pub current_x: f64,
    pub current_y: f64,
    pub is_laser_on: bool,
    pub format_decimals: u8,
    pub scale_factor: f64,
    pub apertures: HashMap<i32, f64>,
    pub current_aperture: i32,
    pub current_d_code: i32,
    pub traces: Vec<LineSegment>,
    pub pins: Vec<SolderPad>
}

impl CncState {
    pub fn new() -> Self {
        CncState {
            current_x: 0.0,
            current_y: 0.0,
            is_laser_on: false,
            format_decimals: 6,
            scale_factor: 1_000_000.0,
            apertures: HashMap::new(),
            current_aperture: 0,
            current_d_code: 2,
            traces: Vec::new(),
            pins: Vec::new()
        }
    }

    pub fn parse_coordinate(&self, raw_val: f64) -> f64 {
        raw_val / self.scale_factor
    }

    pub fn current_thickeness(&self) -> f64 {
        *self.apertures.get(&self.current_aperture).unwrap_or(&1.5)
    }
}

fn extract_coordinates(line: &str, prefix: char) -> Option<f64> {
    if let Some(start_idx) = line.find(prefix) {
        let rest_of_string = &line[start_idx + 1..];
        let end_idx = rest_of_string.find(|c: char| !c.is_ascii_digit() && c != '-' && c != '+').unwrap_or(rest_of_string.len());
        rest_of_string[..end_idx].parse::<f64>().ok()
    } else {
        None
    }
}

#[unsafe(no_mangle)]
pub extern "C" fn process_gerber_to_gcode(path_ptr: *const c_char, feed_rate: i32, laser_power: i32) -> i32 {
    if path_ptr.is_null() {
        return -1; 
    }

    let c_str = unsafe { CStr::from_ptr(path_ptr) };
    
    let file_path = match c_str.to_str() {
        Ok(s) => s,
        Err(_) => return -2, 
    };

    println!("Gtrace Core : Computing File - {}", file_path);
    
    let file = match File::open(file_path){
        Ok(f) => f,
        Err(_e) => {
            println!("Gtrace Core : Failed to open file - {}", file_path);
            return -3;
        } 
    };

    let out_file_path = format!("{}.gcode", file_path);
    let mut out_file = match File::create(&out_file_path) {
        Ok(f) => f,
        Err(_) => return -4,
    };

    writeln!(out_file, "; Generated by GTRACE Core Engine").unwrap();
    writeln!(out_file, "G21 ; Set units to millimeters").unwrap();
    writeln!(out_file, "G90 ; Absolute positioning").unwrap();
    writeln!(out_file, "F{} ; Set feed rate", feed_rate).unwrap();

    let reader = io::BufReader::new(file);

    let mut state = CncState::new();

    println!("Start to prase the garber file :");

    for line_result in reader.lines() {
        let line = match line_result {
            Ok(l) => l,
            Err(_) => continue,
        };

        let line = line.trim();

        if line.is_empty() {
            continue;
        }

        if line.starts_with("G04") {
            continue;
        }

        if line.starts_with("%FSLAX") {
            if let Some(decimal_char) = line.chars().nth(7) {
                if let Some(decimal_num) = decimal_char.to_digit(10_u32) {
                    state.format_decimals = decimal_num as u8;
                    state.scale_factor = f64::powi(10.0, state.format_decimals as i32);

                    println!("Format decimals set to: {}", state.scale_factor);
                }
            }
            continue;
        }

        if line.starts_with("%ADD") {
            println!("Parsing aperture definition: {}", line);

            if let Some(comma_idx) = line.find(',') {
                let prefix = &line[4..comma_idx]; 
                
                let d_code_str: String = prefix.chars().filter(|c| c.is_ascii_digit()).collect();
                let star_idx = line.find('*').unwrap_or(line.len());
                if star_idx > comma_idx {
                    let params = line[comma_idx + 1 .. star_idx].to_uppercase();
                    let size_str = params.split('X').next().unwrap_or("0").trim();
                    
                    if let (Ok(d_code), Ok(size)) = (d_code_str.parse::<i32>(), size_str.parse::<f64>()) {
                        state.apertures.insert(d_code, size);
                        println!("Complete the diameter scan D{} = {} mm", d_code, size);
                    } else {
                        println!("Cant parse the aperture definition D='{}', Size='{}'", d_code_str, size_str);
                    }
                }
            }
            continue;
        }

        if !line.starts_with('%') {

            let old_x = state.current_x;
            let old_y = state.current_y;
            let has_x = extract_coordinates(line, 'X');
            let has_y = extract_coordinates(line, 'Y');
            let d_val = extract_coordinates(line, 'D');

            if let Some(raw_x) = extract_coordinates(line, 'X') {
                state.current_x = state.parse_coordinate(raw_x);
            }
            if let Some(raw_y) = extract_coordinates(line, 'Y') {
                state.current_y = state.parse_coordinate(raw_y);
            }

            let mut should_execute = false;

                if let Some(dv) = d_val {
                    let d_code = dv as i32;
                        
                    if d_code >= 10 {
                        state.current_aperture = d_code;
                        if let Some(size) = state.apertures.get(&d_code) {
                            println!("Selected aperture D{} with size {} mm", d_code, size);
                        }
                    } else {
                        state.current_d_code = d_code;
                        should_execute = true;
                    }
                } else if has_x.is_some() || has_y.is_some() {
                    should_execute = true;
                }

                if should_execute {
                    if state.current_d_code == 1 {
                    state.traces.push(LineSegment {
                        start_x: old_x,
                        start_y: old_y,
                        end_x: state.current_x,
                        end_y: state.current_y,
                        thickness: state.current_thickeness()
                    });
                } else if state.current_d_code == 3 {
                    let pin_size = state.current_thickeness();
                    state.pins.push(SolderPad {
                        x: state.current_x,
                        y: state.current_y,
                        diameter: pin_size
                    });
                    println!("Added pin at X({:.3}, Y{:.3}) with diameter {:.4} mm", state.current_x, state.current_y, pin_size);
                }
            }
        }
    }


    println!("Generating Polygon data from line segments...");

    let mut polygons: Vec<Polygon<f64>> = Vec::new();

    for trace in &state.traces {
        polygons.push(line_to_polygon(trace));

        let r = trace.thickness / 2.0;
        polygons.push(create_circle(trace.start_x, trace.start_y, r));
        polygons.push(create_circle(trace.end_x, trace.end_y, r));
    }

    for pin in &state.pins {
        let r = pin.diameter / 2.0;
        polygons.push(create_circle(pin.x, pin.y, r));
    }

    println!("Converted Line Segments into Polygons: {}", polygons.len());
    
    println!("Performing boolean union on polygons...");

    let mut merged_area: MultiPolygon<f64> = MultiPolygon::new(vec![]);

    for poly in polygons {
        let poly_as_multi = MultiPolygon::new(vec![poly]);
        merged_area = merged_area.union(&poly_as_multi);
    }

    let mut min_x = f64::MAX;
    let mut max_x = f64::MIN;

    

    println!("Polygon Merged complete. Total merged polygons: {}", merged_area.0.len());
    println!("Start to generate Gcode from the merged polygons...");

    for (i, poly) in merged_area.iter().enumerate() {
        writeln!(out_file, "; Polygon {}", i + 1).unwrap();

        let exterior = poly.exterior();
        for (pt_idx, coordinates) in exterior.coords().enumerate() {
            if pt_idx == 0 {
                writeln!(out_file, "G0 X{:.4} Y{:.4} S0", coordinates.x, coordinates.y).unwrap();
            } else {
                writeln!(out_file, "G1 X{:.4} Y{:.4} S{}", coordinates.x, coordinates.y, laser_power).unwrap();
            }
        }

        for interior in poly.interiors() {
            writeln!(out_file, "; Clear the hole").unwrap();
            for (pt_idx, coordinates) in interior.coords().enumerate() {
                if pt_idx == 0 {
                    writeln!(out_file, "G0 X{:.4} Y{:.4} S0", coordinates.x, coordinates.y).unwrap();
                } else {
                    writeln!(out_file, "G1 X{:.4} Y{:.4} S{}", coordinates.x, coordinates.y, laser_power).unwrap();
                }
            }
        }
    }

    writeln!(out_file, "M5 ; Turn off laser").unwrap();
    writeln!(out_file, "M2 ; End of program").unwrap();
    println!("Gtrace Core: Finished processing file - {}", file_path);
    println!("Finished Store the trace data {} line", state.traces.len());
    println!("Finished Store the pin data {} line", state.pins.len());

    1
}
