use std::ffi::CStr;
use std::fs::File;
use std::io::{self, BufRead, Write};
use std::os::raw::c_char;

#[derive(Debug)]
pub struct CncState {
    pub current_x: f64,
    pub current_y: f64,
    pub is_laser_on: bool,
    pub format_decimals: u8,
    pub scale_factor: f64,
}

impl CncState {
    pub fn new() -> Self {
        CncState {
            current_x: 0.0,
            current_y: 0.0,
            is_laser_on: false,
            format_decimals: 6,
            scale_factor: 1_000_000.0,
        }
    }

    pub fn parse_coordinate(&self, raw_val: f64) -> f64 {
    raw_val / self.scale_factor

    }
}

fn extract_coordinates(line: &str, prefix: char) -> Option<f64> {
    if let Some(start_idx) = line.find(prefix) {
        let rest_of_string = &line[start_idx + 1..];
        let end_idx = rest_of_string.find(|c: char| !c.is_ascii_digit() && c != '-' && c != '+').unwrap_or(rest_of_string.len());
        rest_of_string[..end_idx].parse::<f64>().ok()
    } else {
        None
    }
}

#[unsafe(no_mangle)]
pub extern "C" fn process_gerber_to_gcode(path_ptr: *const c_char, feed_rate: i32, laser_power: i32) -> i32 {
    if path_ptr.is_null() {
        return -1; 
    }

    let c_str = unsafe { CStr::from_ptr(path_ptr) };
    
    let file_path = match c_str.to_str() {
        Ok(s) => s,
        Err(_) => return -2, 
    };

    println!("Gtrace Core : Computing File - {}", file_path);
    
    let file = match File::open(file_path){
        Ok(f) => f,
        Err(_e) => {
            println!("Gtrace Core : Failed to open file - {}", file_path);
            return -3;
        } 
    };

    let out_file_path = format!("{}.gcode", file_path);
    let mut out_file = match File::create(&out_file_path) {
        Ok(f) => f,
        Err(_) => return -4,
    };

    writeln!(out_file, "; Generated by GTRACE Core Engine").unwrap();
    writeln!(out_file, "G21 ; Set units to millimeters").unwrap();
    writeln!(out_file, "G90 ; Absolute positioning").unwrap();
    writeln!(out_file, "F{} ; Set feed rate", feed_rate).unwrap();

    let reader = io::BufReader::new(file);

    let mut state = CncState::new();

    println!("Start to prase the garber file :");

    for line_result in reader.lines() {
        let line = match line_result {
            Ok(l) => l,
            Err(_) => continue,
        };

        let line = line.trim();

        if line.is_empty() {
            continue;
        }

        if line.starts_with("G04") {
            continue;
        }

        if line.starts_with("%FSLAX") {
            if let Some(decimal_char) = line.chars().nth(7) {
                if let Some(decimal_num) = decimal_char.to_digit(10_u32) {
                    state.format_decimals = decimal_num as u8;
                    state.scale_factor = f64::powi(10.0, state.format_decimals as i32);

                    println!("Format decimals set to: {}", state.scale_factor);
                }
            }
            continue;
        }

        if !line.starts_with('%') {
            if let Some(raw_x) = extract_coordinates(line, 'X') {
                state.current_x = state.parse_coordinate(raw_x);
            }
            if let Some(raw_y) = extract_coordinates(line, 'Y') {
                state.current_y = state.parse_coordinate(raw_y);
            }

            if let Some(d_code) = extract_coordinates(line, 'D') {
                let d_code = d_code as i32;
                if d_code == 2 {
                    state.is_laser_on = false;
                    writeln!(out_file, "G0 X{:.4} Y{:.4} S0", state.current_x, state.current_y).unwrap();
                } else if d_code == 1 {
                    state.is_laser_on = true;
                    writeln!(out_file, "G1 X{:.4} Y{:.4} S{}", state.current_x, state.current_y, laser_power).unwrap(); 
                } else if d_code == 3 {
                    writeln!(out_file, "G0 X{:.4} Y{:.4} S0", state.current_x, state.current_y).unwrap();
                    writeln!(out_file, "G1 X{:.4} Y{:.4} S{}", state.current_x, state.current_y, laser_power).unwrap(); 
                }
            }
        }
    }

    writeln!(out_file, "M5 ; Turn off laser").unwrap();
    writeln!(out_file, "M2 ; End of program").unwrap();

    println!("Gtrace Core: Finished processing file - {}", file_path);

    1
}
