use std::ffi::CStr;
use std::fs::File;
use std::io::{self, BufRead, Write};
use std::os::raw::c_char;
use std::collections::HashMap;
use geo::{coord, LineString, Polygon, MutiPolygon};
use geo_booleanop::boolean::BooleanOp;

#[derive(Debug)]
pub struct LineSegment {
    pub start_x: f64,
    pub start_y: f64,
    pub end_x: f64,
    pub end_y: f64,
    pub thickness: f64
}

fn line_to_polygon(segment: &LineSegment) -> Polygon<f64> {
    let dx = segment.end_x - segment.start_x;
    let dy = segment.end_y - segment.start_y;
    let length = (dx * dx + dy * dy).sqrt();

    if length == 0.0 {
        let radius = segment.thickness / 2.0;
        let mut points = vec![];
        let sides = 8;

        for i in 0..sides {
            let angle = 2.0 * std::f64::consts::PI * (i as f64) / (sides as f64);
            points.push(coord! {
                x: segment.start_x + radius * angle.cos(),
                y: segment.start_y + radius * angle.sin()
            });
        }
        points.push(points[0]);
        
        return Polygon::new(LineString::new(points), vec![]);
    }

    let nx = -dy / length;
    let ny = dx / length;
    let half_t = segment.thickness / 2.0;

    let p1 = coord! {
        x: segment.start_x + nx * half_t,
        y: segment.start_y + ny * half_t
    };

    let p2 = coord! {
        x: segment.start_x - nx * half_t,
        y: segment.start_y - ny * half_t
    };

    let p3 = coord! {
        x: segment.end_x - nx * half_t,
        y: segment.end_y - ny * half_t
    };

    let p4 = coord! {
        x: segment.end_x + nx * half_t,
        y: segment.end_y + ny * half_t
    };

    Polygon::new(LineString::new(vec![p1, p2, p3, p4, p1]), vec![])
}

#[derive(Debug)]
pub struct CncState {
    pub current_x: f64,
    pub current_y: f64,
    pub is_laser_on: bool,
    pub format_decimals: u8,
    pub scale_factor: f64,
    pub apertures: HashMap<i32, f64>,
    pub current_aperture: i32,
    pub segments: Vec<LineSegment>
}

impl CncState {
    pub fn new() -> Self {
        CncState {
            current_x: 0.0,
            current_y: 0.0,
            is_laser_on: false,
            format_decimals: 6,
            scale_factor: 1_000_000.0,
            apertures: HashMap::new(),
            current_aperture: 0,
            segments: Vec::new()
        }
    }

    pub fn parse_coordinate(&self, raw_val: f64) -> f64 {
        raw_val / self.scale_factor
    }

    pub fn current_thickeness(&self) -> f64 {
        *self.apertures.get(&self.current_aperture).unwrap_or(&0.1)
    }
}

fn extract_coordinates(line: &str, prefix: char) -> Option<f64> {
    if let Some(start_idx) = line.find(prefix) {
        let rest_of_string = &line[start_idx + 1..];
        let end_idx = rest_of_string.find(|c: char| !c.is_ascii_digit() && c != '-' && c != '+').unwrap_or(rest_of_string.len());
        rest_of_string[..end_idx].parse::<f64>().ok()
    } else {
        None
    }
}

#[unsafe(no_mangle)]
pub extern "C" fn process_gerber_to_gcode(path_ptr: *const c_char, feed_rate: i32, _laser_power: i32) -> i32 {
    if path_ptr.is_null() {
        return -1; 
    }

    let c_str = unsafe { CStr::from_ptr(path_ptr) };
    
    let file_path = match c_str.to_str() {
        Ok(s) => s,
        Err(_) => return -2, 
    };

    println!("Gtrace Core : Computing File - {}", file_path);
    
    let file = match File::open(file_path){
        Ok(f) => f,
        Err(_e) => {
            println!("Gtrace Core : Failed to open file - {}", file_path);
            return -3;
        } 
    };

    let out_file_path = format!("{}.gcode", file_path);
    let mut out_file = match File::create(&out_file_path) {
        Ok(f) => f,
        Err(_) => return -4,
    };

    writeln!(out_file, "; Generated by GTRACE Core Engine").unwrap();
    writeln!(out_file, "G21 ; Set units to millimeters").unwrap();
    writeln!(out_file, "G90 ; Absolute positioning").unwrap();
    writeln!(out_file, "F{} ; Set feed rate", feed_rate).unwrap();

    let reader = io::BufReader::new(file);

    let mut state = CncState::new();

    println!("Start to prase the garber file :");

    for line_result in reader.lines() {
        let line = match line_result {
            Ok(l) => l,
            Err(_) => continue,
        };

        let line = line.trim();

        if line.is_empty() {
            continue;
        }

        if line.starts_with("G04") {
            continue;
        }

        if line.starts_with("%FSLAX") {
            if let Some(decimal_char) = line.chars().nth(7) {
                if let Some(decimal_num) = decimal_char.to_digit(10_u32) {
                    state.format_decimals = decimal_num as u8;
                    state.scale_factor = f64::powi(10.0, state.format_decimals as i32);

                    println!("Format decimals set to: {}", state.scale_factor);
                }
            }
            continue;
        }

        if line.starts_with("%ADD") {
            if let Some(c_idx) = line.find("C"){
                if let Ok(d_code) = line[4..c_idx].parse::<i32>() {
                    if let Some(comma_idx) = line.find(','){
                        let star_idx = line.find('*').unwrap_or(line.len());
                        if let Ok(size) = line[comma_idx + 1..star_idx].parse::<f64>() {
                            state.apertures.insert(d_code, size);
                            println!("Defined aperture D{} with size {}", d_code, size);
                        }
                    }
                }
            }
            continue;
        }

        if !line.starts_with('%') {

            let old_x = state.current_x;
            let old_y = state.current_y;

            if let Some(raw_x) = extract_coordinates(line, 'X') {
                state.current_x = state.parse_coordinate(raw_x);
            }
            if let Some(raw_y) = extract_coordinates(line, 'Y') {
                state.current_y = state.parse_coordinate(raw_y);
            }

            if let Some(d_code) = extract_coordinates(line, 'D') {
                let d_code = d_code as i32;
                
                if d_code >= 10 {
                    state.current_aperture = d_code;
                    if let Some(size) = state.apertures.get(&d_code) {
                        println!("Selected aperture D{} with size {}", d_code, size);
                    }
                } else if d_code >= 2 {
                    state.is_laser_on = false;

                } else if d_code == 1 {
                    state.is_laser_on = true;
                    state.segments.push(LineSegment {
                        start_x: old_x,
                        start_y: old_y,
                        end_x: state.current_x,
                        end_y: state.current_y,
                        thickness: state.current_thickeness()
                    });
                } else if d_code == 3 {
                    state.segments.push(LineSegment {
                        start_x: state.current_x,
                        start_y: state.current_y,
                        end_x: state.current_x,
                        end_y: state.current_y,
                        thickness: state.current_thickeness()
                    })
                }
            }
        }
    }

    println!("Generating Polygon data from line segments...");

    let mut polygons: Vec<Polygon<f64>> = Vec::new();

    for segement in &state.segments {
        polygons.push(line_to_polygon(segement));
    }
    
    println!("Converted Line Segments into Polygons: {}", polygons.len());
    println!("Gtrace Core: Finished processing file - {}", file_path);
    println!("Finished Store the trace data {} line", state.segments.len());

    1
}
